spring:
  application:
    name: example-spring-lock

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1
    timeout: 60000ms
    redis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 9
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 9
        # 连接池中的最小空闲连接
        min-idle: 1

app:
  lock:
    prefix: module_name:lock
    default-expire-millis: 60000