spring:
  application:
    name: example-spring-mvc

  datasource:
    url: jdbc:mysql://localhost:3306/example?useUnicode=true&useSSL=true&characterEncoding=utf8&serverTimezone=UTC
    username: example
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        jdbc.time_zone: UTC
        dialect: org.hibernate.dialect.MySQL55Dialect
    #解决驼峰命名自动转为_导致字段找不到的问题
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
